/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.joselion.jupiterloggerplugin;

import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.gradle.api.Project;

/**
 * A simple unit test for the 'com.github.joselion.jupiterloggerplugin.greeting' plugin.
 */
public class JupiterLoggerPluginPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.github.joselion.jupiterloggerplugin.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
